FROM resin/%%BALENA_MACHINE_NAME%%-node

RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app

COPY package.json /usr/src/app/
COPY package-lock.json /usr/src/app/

RUN npm install

COPY . /usr/src/app
RUN npm run build
# RUN npm prune --production

EXPOSE 8080
EXPOSE 56745
EXPOSE 9229

CMD ["npm","run","start:dev"]